/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taptapgo.Server;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import taptapgo.GreetClient;
import taptapgo.TapTapFrame;
/**
 *
 * @author ACER
 */
public class ServerUI extends javax.swing.JFrame {
    private EchoMultiServer server;
    public ServerThread serverThread;
    private List<String> clients;
    
    
    
    /**
     * Creates new form ServerUI
     */
    public ServerUI() {
        initComponents();
        server = new EchoMultiServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtserver = new javax.swing.JTextField();
        txtport = new javax.swing.JTextField();
        btnstartserver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        btnstartclient = new javax.swing.JButton();
        txtstatus = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlinepane = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        btnstartgame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        p1Name = new javax.swing.JLabel();
        p2Name = new javax.swing.JLabel();
        p1Score = new javax.swing.JLabel();
        p2Score = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TapTapGo Server");

        jLabel2.setText("Server");

        jLabel3.setText("Port");

        btnstartserver.setText("Start Server");
        btnstartserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartserverActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jScrollPane2.setViewportView(textpane);

        btnstartclient.setText("Start Client");
        btnstartclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartclientActionPerformed(evt);
            }
        });

        txtstatus.setText("Not Connected");

        jScrollPane3.setViewportView(onlinepane);

        jLabel6.setText("Online User");

        btnstartgame.setText("Start Game");
        btnstartgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartgameActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        p1Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Name.setText("Player");

        p2Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Name.setText("Player");

        p1Score.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        p1Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Score.setText("0");

        p2Score.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        p2Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Score.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(249, 249, 249))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstatus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtserver, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnstartclient))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtport, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnstartgame)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(p1Name, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(p1Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(p2Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 184, Short.MAX_VALUE))
                                    .addComponent(btnstartserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnstartserver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstatus)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnstartclient)
                            .addComponent(btnstartgame))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1Name)
                            .addComponent(p2Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p2Score, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(p1Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartserverActionPerformed
        if(btnstartserver.getText().equals("Start Server")){
            if(!txtserver.getText().isEmpty() && !txtport.getText().isEmpty()){
                txtstatus.setText("Connected");
                btnstartserver.setText("Stop Client");
                serverThread = new ServerThread(Integer.valueOf(ServerUI.txtport.getText()));
                serverThread.start();
                textpane.setText(textpane.getText()+"Server Started on port "+txtport.getText()+"\n");
            }else{
                JOptionPane.showMessageDialog(this, "server name and port should not empty", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            serverThread.stopServer();
            textpane.setText(textpane.getText()+"Server Stopped\n");
            btnstartserver.setText("Start Server");
            txtstatus.setText("Not Connected");
        }
    }//GEN-LAST:event_btnstartserverActionPerformed

    private void btnstartclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartclientActionPerformed
        if(txtstatus.getText().equals("Connected")){
            GreetClient client = new GreetClient();
            client.startConnection(txtserver.getText(), Integer.valueOf(txtport.getText()));
            SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");
            String message = time.format(new Date())+"-> "+txtname.getText()+" Connect \n";
            textpane.setText(textpane.getText() +client.sendMessage(message)+"\n");
            onlinepane.setText(onlinepane.getText() + txtname.getText() + "\n");
            
        }else{
            JOptionPane.showMessageDialog(this, "Please connect to server!", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnstartclientActionPerformed

    private void btnstartgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartgameActionPerformed
        String players[] = onlinepane.getText().split("\n");
        p1Name.setText(players[0]);
        p2Name.setText(players[1]);
        for(String player:players){
            TapTapFrame client = new TapTapFrame(player);
            client.setVisible(true);
            client.t.start();
        }
        
    }//GEN-LAST:event_btnstartgameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstartclient;
    private javax.swing.JButton btnstartgame;
    private javax.swing.JButton btnstartserver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane onlinepane;
    public static javax.swing.JLabel p1Name;
    public static javax.swing.JLabel p1Score;
    public static javax.swing.JLabel p2Name;
    public static javax.swing.JLabel p2Score;
    public static javax.swing.JTextPane textpane;
    private javax.swing.JTextField txtname;
    public static javax.swing.JTextField txtport;
    public static javax.swing.JTextField txtserver;
    private javax.swing.JLabel txtstatus;
    // End of variables declaration//GEN-END:variables
}
